### ISSUE TITLE
15 - Deve permitir a visualização de algoritmos (5)

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/32bits#15]
A visualização de algoritmos é uma técnica que permite ao estudante ver o passo a passo de execução do seu algoritmo (como se fosse um debug), visualizando: a) a sequência de linhas executadas e b) as variáveis alocadas na memória. Assim pode entender o comportamento do seu algoritmo.

Exemplos (veja antes de ler o resto):

http://pythontutor.com/visualize.html#mode=edit
https://www.youtube.com/watch?v=t0Ka9ZUdM5k

Backend (Leonardo):

- [x] Deve-se receber um algoritmo em texto e produzir o stacktrace de sua execução
- [x] Deve-se produzir um JSON com o stacktrace da execução do algoritmo
- [x] Deve-se construir um webservice que irá receber o algoritmo do frontend
- [x] Deve-se construir um webservice que irá retornar o json com o stacktrace do algoritmo

Frontend:

* Incluir um botão no editor de códigos chamado "Visualizar execução".
    - [x] Ao clicar no botão deve fazer uma requisição para um webservice (OBS: existe um código similar que é chamado quando se clica no botão executar de editor.component, pode usar como base)
    - [x] Será recebido um JSON com o detalhe da execução (ver código abaixo). Todo o funcionamento a seguir terá como referência esse Json.
* Criar um componente com os botões de controle da visualização:
    - [x] Terá 2 botões: avançar e voltar. Ao clicar em avançar seguirá para a linha dois do código e assim sucessivamente; Parecido com o Debug do Eclipse/Netbeans
    - [x] Deve-se destacar no editor a linha em que está a execução do algoritmo (cor verde) 
@lsoaresesilva perguntar para mim..
        * A visualização inicia na linha 1 do algoritmo;
        * Ao passar para a próxima linha, a linha anterior perde a cor verde.
* Criar um componente para visualizar as variáveis criadas
    - [x] Para cada variável deve-se criar um pequeno retângulo e dentro dele colocar o nome da variável e o seu valor. Esse retângulo será alterado a medida que o código seja lida e o valor da variável seja modificado.
    * Toda a visualização será trabalhada a partir do JSON descrito abaixo

Dois exemplos de código e JSON que será recebido:

Código a):

a = 2
x = 3
y = 4

JSON a):

{
  "code": "a = 2\nx = 3\ny = 4",
  "trace": [
    {
      "line": 1,
      "event": "step_line",
      "func_name": "<module>",
      "globals": {},
      "ordered_globals": [],
      "stack_to_render": [],
      "heap": {},
      "stdout": ""
    },
    {
      "line": 2,
      "event": "step_line",
      "func_name": "<module>",
      "globals": {
        "a": 2
      },
      "ordered_globals": [
        "a"
      ],
      "stack_to_render": [],
      "heap": {},
      "stdout": ""
    },
    {
      "line": 3,
      "event": "step_line",
      "func_name": "<module>",
      "globals": {
        "a": 2,
        "x": 3
      },
      "ordered_globals": [
        "a",
        "x"
      ],
      "stack_to_render": [],
      "heap": {},
      "stdout": ""
    },
    {
      "line": 3,
      "event": "return",
      "func_name": "<module>",
      "globals": {
        "a": 2,
        "x": 3,
        "y": 4
      },
      "ordered_globals": [
        "a",
        "x",
        "y"
      ],
      "stack_to_render": [],
      "heap": {},
      "stdout": ""
    }
  ]
}

O que importa neste JSON é o atributo  trace que é um array com o passo a passo de execução do algoritmo. Cada objeto desse array possui um atributo **line** que indica em qual linha está a execução e será usado para destacar no editor de código essa linha, e globals que indica quais variáveis estão na memória e o seu respectivo valor.

# Funcionalidades futuras:

* Permitir definir um breakpoint;
* Quando for usado o comando print, antes de entrar na linha, apresentar um pop up para que o estudante preveja qual será o valor. Fazer o mesmo com ifs (perguntar em qual entrará) e for. (2)
* pensar em como incluir um comentário para cada linha explicando o algoritmo (2)
* pensar em como permitir ao aluno modificar os valores do programa é visualizar o comportamento do algoritmo

**Comment by arthur007110** [comment]
@lsoaresesilva no caso será uma área onde mostra o código com as etapas de execução e outra com elementos visuais?

**Comment by lsoaresesilva** [comment]
Acessa: http://localhost:4200/main/(principal:editor). As etapas de execução serão mostradas nesse editor do código, tipo um debug (já usou?). A parte visual vai aparecer em outro componente à direita do editor.

**Comment by lsoaresesilva** [comment]
@arthur007110 faz o seguinte, os botões avançar e voltar coloca no componente de editor. Mas coloca eles dentro de um <div> vizinho ao botão de executar o código. O div deve ter um *ngIf para verificar se está no modo de visualização (variável modoVisualizacao) que estará no componente EditorProgramacaoComponent. É um booleano.

Ao clicar no botão: "Visualizar execução" ele irá ativar modoVisualização para true e deve incluir esse componente no lugar do componente de visualização dos resultados do algoritmo que está no HTML de EditorProgramacaoComponente na linha 53. Em resumo, se estiver no modo visualização não há resposta para o algoritmo. Se não estiver, há, pois estaria no modo de edição normal
