### ISSUE TITLE
25 - Reflexão sobre a execução do planejamento

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/32bits#25]
A reflexão sobre a execução do planejamento é um passo importante para que o estudante tome ciência sobre quais ações ele realizou e que contribuíram para o sucesso/fracasso, e possa assim corrigir ou manter o que for necessário.

Critérios de aceitação:

- [x] Deve ser criado um componente:
- [x] - Qual o seu nível de confiança de que compreendeu esse conteúdo? Usar um Slide. (Ref: Prompting in web-based environments: Supporting self-monitoring and problem solving skills in college students)
- [x] Deve ter um campo para que o estudante escreva: Quais foram as suas dificuldades com o conteúdo?
- [x]  Deve ter um campo de texto para que o estudante reflita sobre quais ações que ele realizou e que podem ter contribuído para o seu aprendizado
       * A FAZER: Verificar a possibilidade do sistema identificar isso automaticamente comparando ações realizadas por estudantes que se deram bem e as ações dos estudantes que se deram mal
- [x] O que você poderia ter feito que iria melhorar o seu aprendizado?
- [x] Deve ter um botão "Salvar" e ao clicá-lo:
    - [x] As informações devem ser salvas no banco de dados na collection: autoreflexao_srl
    - [x] Se a operação for realizada com sucesso redirecionar para o componente de listagem de planejamentos
    - [x] Em caso contrário exibir a mensagem de erro.

# Referências:

1. The educational affordances of blogs for self-directed learning
2. Fostering Self-Regulated learning in Introductory Computer Programming Course

**Comment by evicsouza** [comment]
Vai ser uma nova tela, que vai ser aberta no fim de toda "atividade" do estudante, ne?

**Comment by lsoaresesilva** [comment]
O seu componente será incluído Na tela de planejamento do estudo #27. Quando o estudante concluir todo o planejamento (envolve leitura de material e realização das atividades). Mas pra você isso não importa muito, é transparente, pois alguém vai simplesmente fazer uma chamada ao seu componente, sem que você saiba quando.

**Comment by evicsouza** [comment]
Acho que terminei :) vê se tá Ok
