### ISSUE TITLE
Deve ser possível visualizar um código similar à questão

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/32bits#7]
O estudante pode visualizar o código de referência para a questão. O código deve ser similar, mas não igual à questão. Deve servir de referência para 

Critérios de aceitação:

- [x] Criar um component para que uma resposta para uma questão seja feita
    - [x] A resposta é um texto ques será um algoritmo que um professor irá escrever
    - [x] O professor deve indicar à qual questão a resposta pertence (primeiro aparecerão os assuntos, após selecionar um assunto aparecerão as questões, e aí ele seleciona. Pode-se usar um dropdown ou algo parecido)
- [x] A resposta será salva em um Document de nome ModeloRespostaQuestao(id, questaoId, codigo)
- [x] Deve criar um outro component que será utilizado para exibir a solução da questão
    - [x] Ao visualizar a solução para uma questão o sistema deve  indicar que o status da questão é que ele visualizou a solução. Essa informação será salva no banco de dados no document VisualizacaoRespostasQuestoes(id, modeloRespostaQuestaoId, usuarioId). Fazer isso no ngOnInit do component.

**Comment by Wanessaa** [comment]
Devido o get do modeloRespostaQuestao não funcionar está dando erro quando vai exibir o modelo no componente resposta-similar-questao.
E está com problema a função verificaModeloExiste pois o getAll n busca todos os modelos.
